/**
 * skills.js — grouped by what the work actually is, not by vendor.
 *
 * `lead` renders as filled chips (in regular use); `rest` renders quietly
 * behind it (shipped with, would pick back up). `axis` only picks the accent
 * colour here — it carries no meaning the way it does on the timeline.
 */

export const skillGroups = [
  {
    title: 'Medical imaging & 3D',
    axis: 'si',
    lead: ['DICOM', 'VTK', 'ITK / SimpleITK', '3D Registration', 'Volumetric Segmentation'],
    rest: [
      'Multimodal Fusion (CT / MR)',
      'Rigid & Deformable Registration',
      'Mutual Information Alignment',
      'Point Cloud Processing',
      'ICP',
      'Skull Stripping',
      'Surface Reconstruction',
      'DTI / DWI Tractography',
      'Trajectory Planning',
      'Structured Light Capture',
      'FRE / TRE Validation',
      'Open3D',
      'nibabel',
      '3D Slicer',
    ],
  },
  {
    title: 'Machine learning & vision',
    axis: 'lr',
    lead: ['PyTorch', 'Computer Vision', 'Deep Learning', 'Transformers', 'CNNs'],
    rest: [
      'TensorFlow',
      'scikit-learn',
      'HuggingFace',
      'OpenCV',
      'ResNet50',
      'U-Net',
      'YOLO',
      'DistilBERT',
      'MONAI',
      'Semantic Segmentation',
      'Object Detection',
      'Transfer Learning',
      'PEFT / LoRA',
      'Quantization',
      'Model Evaluation',
      'spaCy',
    ],
  },
  {
    title: 'LLM systems',
    axis: 'ap',
    lead: ['RAG', 'LangChain', 'Agentic Workflows', 'Prompt Engineering', 'Vector Search'],
    rest: [
      'LlamaIndex',
      'Graph RAG',
      'Azure OpenAI',
      'OpenAI API',
      'GPT-4o',
      'Claude',
      'Ollama',
      'Qwen3',
      'Embeddings',
      'Semantic Chunking',
      'Chain-of-Thought',
      'Structured Output',
      'Function Calling',
      'deepeval',
      'Argilla',
      'LLM-as-a-Judge',
    ],
  },
  {
    title: 'Languages & frameworks',
    axis: 'si',
    lead: ['Python', 'C++', 'SQL', 'FastAPI', 'PyQt'],
    rest: [
      'Cypher',
      'Bash',
      'JavaScript',
      'NumPy',
      'SciPy',
      'pandas',
      'Pydantic',
      'Flask',
      'Streamlit',
      'AngularJS',
      'REST APIs',
      'pytest',
      'Selenium',
      'Qt',
    ],
  },
  {
    title: 'Data & infrastructure',
    axis: 'ap',
    lead: ['PostgreSQL', 'Neo4j', 'Docker', 'AWS', 'CI/CD'],
    rest: [
      'pgvector',
      'Qdrant',
      'MongoDB',
      'MySQL',
      'Apache Kafka',
      'Apache Spark',
      'Spark Streaming',
      'Databricks',
      'HDFS',
      'Elasticsearch',
      'Kibana',
      'Kubernetes',
      'OpenShift',
      'Jenkins',
      'GitHub Actions',
      'MLflow',
      'Linux',
      'Git',
    ],
  },
  {
    title: 'Regulated software',
    axis: 'lr',
    lead: ['IEC 62304', 'ISO 14971', 'ISO 13485', 'FDA 510(k) V&V'],
    rest: [
      'IEC 62366-1',
      'ISO 27001',
      '21 CFR Part 11',
      'HIPAA',
      'GDPR',
      'Design Controls',
      'Requirements Traceability',
      'Risk Management',
      'SOUP Evaluation',
      'Verification & Validation',
      'DICOM De-identification',
      'Role-Based Access Control',
      'Audit Logging',
    ],
  },
];
